//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Czytam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class CzytamAppEntities1 : DbContext
    {
        public CzytamAppEntities1()
            : base("name=CzytamAppEntities1")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<exercis> exercises { get; set; }
        public virtual DbSet<exercises_setup> exercises_setup { get; set; }
        public virtual DbSet<lesson> lessons { get; set; }
        public virtual DbSet<lessons_setup> lessons_setup { get; set; }
        public virtual DbSet<syllable> syllables { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<word> words { get; set; }
    }
}
