//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Czytam
{
    using System;
    using System.Collections.Generic;
    
    public partial class exercis
    {
        public int id { get; set; }
        public int lesson_id { get; set; }
        public bool is_done { get; set; }
        public int exercise_number { get; set; }
    
        public virtual lesson lesson { get; set; }
    }
}
